version: '2'
services:
  app:
    build:
      context: .
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: app_development
    ports:
      - "3000:3000"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - 3306:3306
    volumes:
      - mysql-db:/var/lib/mysql

  console:
    build:
      context: .
      dockerfile: Dockerfile-console
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: app_development
    volumes:
      - .:/srv
    depends_on:
      - db
    stdin_open: true

volumes:
  mysql-db:
    driver: local
